name:                sound-supercollider
version:             0.1
github:              "mlang/sound-supercollider"
license:             BSD3
author:              "Mario Lang"
maintainer:          "mlang@blind.guru"
copyright:           "2022 Mario Lang"

description:         A simple SuperCollider client library

dependencies:
- aeson
- async
- base >= 4.16
- binary
- brick >= 1.5
- bytestring
- containers
- deepseq
- event-list
- exceptions
- groups
- hosc >= 0.20
- microlens
- microlens-contra
- microlens-mtl
- midi
- mtl
- nonempty-containers
- sort
- stm
- stm-chans
- th-lift-instances
- template-haskell
- text
- transformers >= 0.5.3
- typed-process
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -split-sections

library:
  source-dirs: .

executables:
  brick-tracker:
    main:                Main.hs
    source-dirs:         brick-tracker
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick
    - microlens-th
    - sound-supercollider
    - vty
  sound-supercollider-build:
    main:                SynthDefs.hs
    source-dirs:         build
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pretty-simple
    - typed-process
    - sound-supercollider
  sound-supercollider-playmidi:
    main:                Main.hs
    source-dirs:         playmidi
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sound-supercollider
